config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'books/:id' => 'books#show', as:'book'
  get 'books/:id/edit' => 'books#edit', as:'edit_list'
  patch 'books/:id' => 'books#update', as:'update_list'
  delete 'books/:id' => 'books#destroy', as:'destroy_list'
  resources:books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates:title,presence:true
  validates:body,presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def index
        @new = Book.new
        @book = Book.all
    end

    def show
        @book = Book.find(params[:id])
    end

    def edit
        @book = Book.find(params[:id])
    end

    def create
        @new = Book.new(list_params)
     if @new.save
        flash[:notice] = "Book was successfully created."
        redirect_to book_path(@new.id)
     else
        @book = Book.all
        render:index
     end
    end

    def update
        @book = Book.find(params[:id])
    if  @book.update(list_params)
        flash[:notice] = "Book was successfully updated."
        redirect_to book_path(@book.id)
    else
        render:edit
    end
    end

    def destroy
        book = Book.find(params[:id])
        book.destroy
        flash[:notice] = "Book was successfully destroyed."
        redirect_to '/books'
    end

  private

    def list_params
    params.require(:book).permit(:title, :body)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>
<%= @book.errors.count %>errors prohidited this book from being saved:
<ul>
  <% @book.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

<%= form_with model:@book, url: update_list_path(@book.id), method: :patch do |f| %>
  <div class="edit">Title</div>
  <div class="edit"><%= f.text_field:title %></div>
  <div class="edit">Body</div>
  <div class="edit"><%= f.text_area:body %></div>

  <div class="update"><%= f.submit'Update Book' %></div>

  <% end %>

  <span class="menu1"><%= link_to "Show",book_path(@book.id) %></span>

  <%= link_to "Back","/books" %>

app/views/books/index.html.erb
<div class="message">
 <%= flash[:notice] %>
</div>

<h1>Books</h1>
 <table>
    <thead>
      <tr>
       <th class="title">Title</th>
       <th class="body">Body</th>
       <th class="menu",colespan="3"></th>
      </tr>
    </thead>
    <% @book.each do |book| %>
    <tbody>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to "Show",book_path(book.id) %>
           <%= link_to "Edit",edit_list_path(book.id) %>
           <%= link_to "Destroy",destroy_list_path(book.id),method: :delete,"data-confirm" => "本当に削除しますか？" %></td>
       </tr>
    </tbody>
    <% end %>
  </table>

<h2>New book</h2>
  <% if @new.errors.any? %>
    <%= @new.errors.count %>errors prohidited this book from being saved:
 <ul>
   <% @new.errors.full_messages.each do |message| %>
   <li><%= message %></li>
   <% end %>
 </ul>
  <% end %>

  <%= form_with model:@new do |f| %>
  <div class="text">Title</div>
  <div class="text"><%= f.text_field:title %></div>
  <div class="text">Body</div>
  <div class="text"><%= f.text_area:body %></div>
  
  <div class="text"><%= f.submit'Create Book' %></div>
  
<% end %>

app/views/books/show.html.erb
<div class="message">
  <%= flash[:notice] %>
</div>

<p class="show">Title:<%= @book.title %></p>

<p class="show">Body:<%= @book.body %></p>

<span class="menu1"><%= link_to "Edit",edit_list_path(@book.id) %></span>

<%= link_to "Back","/books" %>

app/views/homes/top.html.erb
 <h1>ようこそBookersへ！</h1>　
 　<p class="top">Bookersでは、さまざまな書籍に関するあなたの意見や</p>
   <p class="top">印象を共有し交換できます</p>
　<span class="start"><%= link_to "start","/books" %></span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
      <%= yield %>
  
  </body>
</html>